#+TITLE: Config
#+AUTHOR: DoppleDankster
#+DESCRIPTION: Litterate config 

* Config
** Fonts
Settings related to fonts within Doom Emacs:

-  ‘doom-font’ – standard monospace font that is used for most things in Emacs.
-  ‘doom-variable-pitch-font’ – variable font which is useful in some Emacs plugins.
-  ‘doom-big-font’ – used in doom-big-font-mode; useful for presentations.
-  ‘font-lock-comment-face’ – for comments.
-  ‘font-lock-keyword-face’ – for keywords with special significance, like ‘for’ and ‘if’ in C.

#+begin_src  elisp
(setq doom-font (font-spec :family "Cascadia Code" :size 15)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 15)
      doom-big-font (font-spec :family "Cascadia Code" :size 24))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

** Line Settings
I have toggled display-line-numbers-type so I have line numbers displayed.  Doom Emacs uses ‘SPC t’ for “toggle” commands, so I choose ‘SPC t t’ for toggle-truncate-lines.
#+begin_src elisp
(setq display-line-numbers-type t)
(map! :leader
      :desc "Toggle truncate lines"
      "t t" #'toggle-truncate-lines)
#+end_src

** Mail with MU4E
Setting up mu4e which is an email client that works within emacs.  You must install mu4e and mbsync through your Linux distribution’s package manager. Setting up smtp for sending mail. Make sure the gnutls command line utils are installed. Package ‘gnutls-bin’ in Debian/Ubuntu, and ‘gnutls’ in Arch.
#+begin_src elisp
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
;;(require 'smtpmail)
(setq user-mail-address "davidmedioni@protonmail.com"
      user-full-name  "David MEDIONI"
      ;; I have my mbsyncrc in a different folder on my system, to keep it separate from the
      ;; mbsyncrc available publicly in my dotfiles. You MUST edit the following line.
      ;; Be sure that the following command is: "mbsync -c ~/.config/mu4e/mbsyncrc -a"
      mu4e-get-mail-command "mbsync -c ~/.config/mu4e-dt/mbsyncrc -a"
      mu4e-update-interval  300
      mu4e-main-buffer-hide-personal-addresses t
      message-send-mail-function 'smtpmail-send-it
      starttls-use-gnutls t
      smtpmail-starttls-credentials '(("smtp.1and1.com" 587 nil nil))
      mu4e-sent-folder "/account-1/Sent"
      mu4e-drafts-folder "/account-1/Drafts"
      mu4e-trash-folder "/account-1/Trash"
      mu4e-maildir-shortcuts
      '(("/account-1/Inbox"      . ?i)
        ("/account-1/Sent Items" . ?s)
        ("/account-1/Drafts"     . ?d)
        ("/account-1/Trash"      . ?t)))
#+end_src
** Python
#+begin_src elisp
(use-package! python-black
  :demand t
  :after python)
(add-hook! 'python-mode-hook #'python-black-on-save-mode)
#+end_src
** Golang
